# Generated by Django 6.0.1 on 2026-02-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_alter_review_options_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Төлөндү'),
        ),
        migrations.AddField(
            model_name='order',
            name='prepayment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Взнос (10%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Жалпы баасы'),
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.TextField(verbose_name='Дареги'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имараттын аты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коммент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Күнү'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Жаңы (Төлөм күтүлүүдө)'), ('PAID', 'Взнос төлөндү'), ('IN_PROGRESS', 'Аткарылууда'), ('DONE', 'Аяктады'), ('CANCELLED', 'Жокко чыгарылды')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(verbose_name='Убактысы'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Сүрөттөмөсү'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Кызматтын аты'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баасы'),
        ),
    ]
