# Generated by Django 6.0.1 on 2026-02-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_alter_category_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
