# Generated by Django 6.0.1 on 2026-02-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_remove_user_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Имарат', 'verbose_name_plural': 'Имараттар'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категориялар'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Кардар', 'verbose_name_plural': 'Кардарлар'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказдар'},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name': 'Заказ тарыхы', 'verbose_name_plural': 'Заказ тарыхы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Пикир', 'verbose_name_plural': 'Пикирлер'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Кызмат', 'verbose_name_plural': 'Кызматтар'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Колдонуучу', 'verbose_name_plural': 'Колдонуучулар'},
        ),
    ]
